[package]
name = "chathole"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

anyhow = "1.0.79"
colored = "2.1.0"
tabled = "0.15.0"
use = "0.0.1-pre.0"
watch = "0.2.3"
